<div class="breadcrumbs">
    <div class="col-sm-4">
        <div class="page-header float-left">
            <div class="page-title">
                <h1>Dashboard</h1>
            </div>
        </div>
    </div>
    <div class="col-sm-8">
        <div class="page-header float-right">
            <div class="page-title">
                <ol class="breadcrumb text-right">
                    <li><a href="<?= BASE_URL; ?>admin/">Dashboard</a></li>
                    <li><a href="<?= BASE_URL; ?>admin/usuarios">Usuários</a></li>
                    <li class="active">Índice</li>
                </ol>
            </div>
        </div>
    </div>
</div>   
<div class="content mt-3">
    <div class="animated fadeIn">        
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <strong class="card-title">Usuários cadastrados no sistema</strong>
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Nome</th>
                                <th scope="col">Email</th>
                                <th scope="col">Permissão</th>
                                <th scope="col">Último Acesso</th>
                                <th scope="col">Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($this->viewData['users'] as $usuario):
                                $ultimo_acesso_usuario = $usuario['ultimo_acesso_usuario'] ? date('d/m/Y H:i:s', strtotime($usuario['ultimo_acesso_usuario'])) : 'indisponível';
                                $permissão = ['Administrador', 'Gerente', 'Vendedor'];
                                ?>
                                <tr id="user_<?= $usuario['id_usuario'] ?>">
                                    <th scope="row"><?= $usuario['id_usuario'] ?></th>
                                    <td><a href="<?= BASE_URL ?>admin/usuarios/editar/<?= $usuario['id_usuario'] ?>" title="editar usuário"><?= $usuario['nome_usuario'] ?> <?= $usuario['sobrenome_usuario'] ?></a></td>
                                    <td><?= $usuario['email_usuario'] ?></td>
                                    <td><?= $permissão[$usuario['permissao_usuario'] - 1] ?></td>
                                    <td><?= $ultimo_acesso_usuario; ?></td>
                                    <td>
                                        <a href="<?= BASE_URL ?>admin/usuarios/editar/<?= $usuario['id_usuario'] ?>" title="editar usuário">Editar</a>
                                        <a href="<?= BASE_URL ?>admin/usuarios/delete/<?= $usuario['id_usuario'] ?>" data-name="<?= $usuario['nome_usuario'] ?> <?= $usuario['sobrenome_usuario'] ?>" title="editar usuário" class="user_delete" id="<?= $usuario['id_usuario'] ?>">Excluir</a>
                                    </td>
                                </tr>   
                                <?php
                            endforeach;
                            ?>
                        </tbody>
                    </table>
                    <?php
                    $pager = new App\Helpers\Pager($this->viewData['pagina'], $this->viewData['paginas'], $this->viewData['limit'], $this->viewData['offset'], 'admin/usuarios/pagina');
                    echo $pager->showPager();
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" tabindex="-1" data-keyboard="false" data-backdrop="static" role="dialog" id="modal_usuarios_del">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Exclusão de usuário</h5>
                <button type="button" class="close btn_close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p><i class="fa fa-spinner fa-spin fa-2x fa-fw"></i>Excluindo usuário...</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger btn_close" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>
