<?php

use App\Helpers\Check;
?>
<section id="slider"><!--slider-->
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div id="slider-carousel" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
                        <li data-target="#slider-carousel" data-slide-to="1"></li>
                        <li data-target="#slider-carousel" data-slide-to="2"></li>
                        <li data-target="#slider-carousel" data-slide-to="3"></li>
                    </ol>

                    <div class="carousel-inner">
                        <?php
                        $i = 0;
                        foreach ($this->viewData['slider']as $item):
                            $active = $i == 0 ? ' active' : '';
                            ?>
                            <div class="item<?= $active; ?>">
                                <div class="col-sm-6">
                                    <h1><span>JL</span>-MAGAZINE</h1>
                                    <h2><?= $item['slider_title']; ?></h2>
                                    <p><?= $item['slider_description']; ?> </p>
                                    <button type="button" class="btn btn-default get">Saiba mais</button>
                                </div>
                                <div class="col-sm-6">
                                    <img src="<?= BASE_URL . $this->viewData['cropper']->resize('uploads/' . $item['slider_image'], 484, 441); ?>" class="girl img-responsive" alt="" />
                                    <img src="<?= BASE_URL . $this->viewData['cropper']->resize('uploads/' . $item['slider_sticker'], 172, 172); ?>"  class="pricing img-circle" alt="" />
                                </div>
                            </div>    
                            <?php
                            $i++;
                        endforeach;
                        ?>
                    </div>

                    <a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
                        <i class="fa fa-angle-left"></i>
                    </a>
                    <a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
                        <i class="fa fa-angle-right"></i>
                    </a>
                </div>

            </div>
        </div>
    </div>
</section><!--/slider-->
<section>
    <div class="container">
        <div class="row">            
            <?php
            include_once 'app/views/loja/template/sidebar.phtml';
            ?>
            <div class="col-sm-9 padding-right">
                <div class="features_items"><!--features_items-->

                    <h2 class="title text-center">Produtos em destaque</h2>
                    <?php
                    foreach ($this->viewData['featured_products'] as $prod):
                        $price = number_format($prod['preco_venda_produto'] - $prod['desconto_produto'], 2, ',', '.');
                        $discount = $prod['desconto_produto'] ? 'De R$ ' . number_format($prod['preco_venda_produto'], 2, ',', '.') . ' por ' : '';
                        $new = $prod['created_at'] > date('Y-m-d H:i:s', strtotime("-30 days")) ? true : false;
                        ?>                    
                        <div class="col-sm-4 products-wrapper">
                            <div class="product-image-wrapper">
                                <div class="single-products">
                                    <div class="productinfo text-center">
                                        <picture>
                                            <source media="(max-width: 320px)" srcset="<?= BASE_URL . $this->viewData['cropper']->resize('uploads/' . $prod['imagem_uri'], 260, 380); ?>">
                                            <source media="(max-width: 767px)" srcset="<?= BASE_URL . $this->viewData['cropper']->resize('uploads/' . $prod['imagem_uri'], 690, 1008); ?>">
                                            <img src="<?= BASE_URL . $this->viewData['cropper']->resize('uploads/' . $prod['imagem_uri'], 312, 456); ?>" alt="<?= $prod['titulo_produto']; ?>" />
                                        </picture>
                                        <h2><span><?= $discount; ?></span> R$ <?= $price; ?></h2>
                                        <p><?= Check::Words($prod['titulo_produto'], 10); ?></p>
                                        <a href="<?= BASE_URL; ?>add-product" data-product="<?= $prod['id_produto']; ?>" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Adicionar ao carrrinho</a>
                                    </div>
                                    <div class="product-overlay">
                                        <div class="overlay-content">
                                            <h2><span><?= $discount; ?></span> R$ <?= $price; ?></h2>
                                            <p><?= Check::Words($prod['titulo_produto'], 10); ?></p>
                                            <a href="<?= BASE_URL; ?>add-product" data-product="<?= $prod['id_produto']; ?>" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Adicionar ao carrinho</a>
                                        </div>
                                    </div>
                                    <?= $new && !$prod['sale_produto'] ? '<img src="' . BASE_URL . 'images/home/new.png" class="new" alt="" />' : ''; ?>
                                    <?= $prod['sale_produto'] ? '<img src="' . BASE_URL . 'images/home/sale.png" class="new" alt="" />' : ''; ?>
                                </div>
                                <div class="choose">
                                    <ul class="nav nav-pills nav-justified">
                                        <li><a href="<?= BASE_URL; ?>add-to-wishlist" data-product="<?= $prod['id_produto']; ?>" title="Adicionar à lista de desejos" class="add-to-wishlist"><i class="fa fa-plus-square"></i>lista de desejos</a></li>
                                        <li><a href="<?= BASE_URL; ?>produtos/item/<?= $prod['path_produto']; ?>" title="Ver produto"><i class="fa fa-arrow-right"></i>ver produto</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <?php
                    endforeach;
                    ?>

                </div><!--features_items-->
                <?php
                if ($this->viewData['display']['recommended_products']):
                    ?>
                    <div class="recommended_items"><!--recommended_items-->
                        <h2 class="title text-center">Recomendados</h2>

                        <div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                <?php
                                $c = 0;
                                $size = count($this->viewData['recommended']);
                                foreach ($this->viewData['recommended'] as $re):
                                    echo $c == 0 ? '<div class="item active">' : '';
                                    $c++;
                                    $price = number_format($re['preco_venda_produto'] - $re['desconto_produto'], 2, ',', '.');
                                    ?>
                                    <div class="col-sm-4">
                                        <div class="product-image-wrapper">
                                            <div class="single-products">
                                                <div class="productinfo text-center">
                                                    <img src="<?= BASE_URL . $this->viewData['cropper']->resize('uploads/' . $re['imagem_uri'], 268, 200, 't'); ?>" alt="" />
                                                    <h2>R$ <?= $price; ?></h2>
                                                    <p><?= Check::Words($re['titulo_produto'], 10); ?></p>
                                                    <a href="<?= BASE_URL; ?>add-product" data-product="<?= $re['id_produto']; ?>" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Adicionar ao carrinho</a>
                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                    <?php
                                    echo $c % 3 == 0 ? '</div>' : $c == $size ? '</div>' : '';
                                    echo $c % 3 == 0 && $c < $size ? '<div class="item">' : '';
                                endforeach;
                                ?>

                            </div>
                            <a class="left recommended-item-control" href="prev#recommended-item-carousel" data-slide="prev">
                                <i class="fa fa-angle-left"></i>
                            </a>
                            <a class="right recommended-item-control" href="next#recommended-item-carousel" data-slide="next">
                                <i class="fa fa-angle-right"></i>
                            </a>			
                        </div>
                    </div><!--/recommended_items-->
                    <?php
                endif;
                ?>
            </div>
        </div>
    </div>
</section>  