<section id="form"><!--form-->
    <div class="container">
        <div class="row">
            <div class="col-sm-4 col-sm-offset-1">
                <div class="login-form"><!--login form-->
                    <div class="debug"></div>
                    <div class="alert alert-form  alert-warning"></div>
                    <h2>Já sou cadastrado</h2>
                    <form method="post" name="client_login">
                        <input type="email" name="email_cliente" placeholder="Email" />
                        <input type="password" name="senha_cliente" placeholder="Senha" />
                        <span>
                            <input type="checkbox" name="keep_logged_in" class="checkbox">
                            Permancecer logado!
                        </span>
                        <button type="submit" class="btn btn-default">Login <i class="fa fa-spinner fa-pulse fa-fw hide"></i></button>
                    </form>
                </div><!--/login form-->
            </div>
            <div class="col-sm-1">
                <h2 class="or">Ou</h2>
            </div>
            <div class="col-sm-4">
                <div class="signup-form"><!--sign up form-->
                    <div class="alert alert-form  alert-warning"></div>
                    <h2>Quero me cadastrar!</h2>
                    <form name="signup_form" method="post">
                        <input type="text" placeholder="Nome" name="nome_cliente"/>
                        <input type="email" placeholder="Email" name="email_cliente"/>
                        <input type="password" placeholder="Senha" name="senha_cliente"/>
                        <button type="submit" class="btn btn-default">Cadastrar <i class="fa fa-spinner fa-pulse fa-fw"></i></button>
                    </form>
                </div><!--/sign up form-->
            </div>
        </div>
    </div>
</section><!--/form-->