<section id="thank_you"><!--form-->
    <div class="container">
        <div class="row">
            <div class="col-sm-12 thank_you_wrapper">
                <h1>Obrigado pela compra</h1>
                <p>Em breve você receberá a confirmação da compra no seu e-mail.</p>
                <p>Em caso de dúvida com o seu pedido entre em contato conosco</p>
                <div class="company_name">
                    <p><?= SITENAME; ?> - tel: 84 999 9999</p>
                </div>
            </div>
        </div>
    </div>
</section>