<?php

use App\Helpers\Check;

if ($this->viewData['display']['recommended_products']):
    ?>
    <div class="recommended_items"><!--recommended_items-->
        <h2 class="title text-center">Recomendados</h2>

        <div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <?php
                $c = 0;
                $size = count($this->viewData['recommended']);
                foreach ($this->viewData['recommended'] as $re):
                    echo $c == 0 ? '<div class="item active">' : '';
                    $c++;
                    $price = number_format($re['preco_venda_produto'] - $re['desconto_produto'], 2, ',', '.');
                    ?>
                    <div class="col-sm-4">
                        <div class="product-image-wrapper">
                            <div class="single-products">
                                <div class="productinfo text-center">
                                    <img src="<?= BASE_URL . $this->viewData['cropper']->make('uploads/' . $re['imagem_uri'], 268, 300); ?>" alt="" />
                                    <h2>R$ <?= $price; ?></h2>
                                    <p><?= Check::Words($re['titulo_produto'], 10); ?></p>
                                    <a href="<?= BASE_URL; ?>add-product" data-product="<?= $re['id_produto']; ?>" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Adicionar ao carrinho</a>
                                </div>

                            </div>
                        </div>
                    </div>
                    <?php
                    echo $c % 3 == 0 ? '</div>' : $c == $size ? '</div>' : '';
                    echo $c % 3 == 0 && $c < $size ? '<div class="item">' : '';
                endforeach;
                ?>

            </div>
            <a class="left recommended-item-control" href="prev#recommended-item-carousel" data-slide="prev">
                <i class="fa fa-angle-left"></i>
            </a>
            <a class="right recommended-item-control" href="next#recommended-item-carousel" data-slide="next">
                <i class="fa fa-angle-right"></i>
            </a>			
        </div>
    </div><!--/recommended_items-->
    <?php
endif;
