<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
    <!--<![endif]-->

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Sufee Admin - HTML5 Admin Template</title>
        <meta name="description" content="Sufee Admin - HTML5 Admin Template">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <meta name="base-url" content="<?= BASE_URL; ?>admin/">

        <link rel="apple-touch-icon" href="apple-icon.png">
        <link rel="shortcut icon" href="favicon.ico">


        <link rel="stylesheet" href="<?= BASE_URL; ?>lib/bootstrap/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="<?= BASE_URL; ?>lib/font-awesome/css/font-awesome.min.css">
        <link rel="stylesheet" href="<?= BASE_URL; ?>lib/themify-icons/css/themify-icons.css">
        <link rel="stylesheet" href="<?= BASE_URL; ?>lib/flag-icon-css/css/flag-icon.min.css">
        <link rel="stylesheet" href="<?= BASE_URL; ?>lib/selectFX/css/cs-skin-elastic.css">

        <link rel="stylesheet" href="<?= BASE_URL; ?>assets/css/style.css">

        <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>



    </head>

    <body class="bg-dark">


        <div class="sufee-login d-flex align-content-center flex-wrap">
            <div class="container">
                <div class="login-content">
                    <div class="login-logo">
                        <a href="index.html">
                            <img class="align-content" src="images/logo.png" alt="">
                        </a>
                    </div>
                    <div class="login-form">
                        <div id="login_msg"></div>
                        <form name="formLogin" action="" method="post">
                            <div class="form-group">
                                <label>Email</label>
                                <input type="email" class="form-control" name="email_usuario" placeholder="Email">
                            </div>
                            <div class="form-group">
                                <label>Senha</label>
                                <input type="password" class="form-control" name="senha_usuario" placeholder="Password">
                            </div>
                            <div class="checkbox">
                                <!-- <label>
                                    <input type="checkbox"> Remember Me
                                </label>-->
                                <label class="pull-right">
                                    <a href="#">Esqueceu a senha?</a>
                                </label>

                            </div>
                            <button type="submit" class="btn btn-success btn-flat m-b-30 m-t-30">Sign in</button>
                            <!--                                <div class="social-login-content">
                                                                <div class="social-button">
                                                                    <button type="button" class="btn social facebook btn-flat btn-addon mb-3"><i class="ti-facebook"></i>Sign in with facebook</button>
                                                                    <button type="button" class="btn social twitter btn-flat btn-addon mt-2"><i class="ti-twitter"></i>Sign in with twitter</button>
                                                                </div>
                                                            </div>-->
                            <div class="register-link m-t-15 text-center">
                                <p>Não tem uma conta? <a href="#"> Cadastre-se!</a></p>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <script src="<?= BASE_URL; ?>lib/jquery/dist/jquery.min.js" type="text/javascript"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
        <script src="<?= BASE_URL; ?>assets/js/main.js"></script>
        <script src="<?= BASE_URL; ?>assets/js/login.js"></script>


    </body>

</html>
