<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="pt-br">
    <!--<![endif]-->

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title><?= SITENAME;?> | Sufee Admin - HTML5 Admin Template</title>
        <meta name="description" content="Sufee Admin - HTML5 Admin Template">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <meta name="base-url" content="<?= BASE_URL; ?>admin/">

        <link rel="apple-touch-icon" href="<?= BASE_URL; ?>apple-icon.png">
        <link rel="shortcut icon" href="<?= BASE_URL; ?>favicon.ico">

        <link rel="stylesheet" href="<?= BASE_URL;?>lib/bootstrap/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="<?= BASE_URL;?>lib/font-awesome/css/font-awesome.min.css">
        <link rel="stylesheet" href="<?= BASE_URL;?>lib/themify-icons/css/themify-icons.css">
        <link rel="stylesheet" href="<?= BASE_URL;?>lib/flag-icon-css/css/flag-icon.min.css">
        <link rel="stylesheet" href="<?= BASE_URL;?>lib/selectFX/css/cs-skin-elastic.css">
        <link rel="stylesheet" href="<?= BASE_URL;?>lib/jqvmap/dist/jqvmap.min.css">


        <link rel="stylesheet" href="<?= BASE_URL;?>assets/css/style.css">
        <link rel="stylesheet" href="<?= BASE_URL;?>assets/css/admin.css">

        <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>

    </head>

    <body>


        <!-- Left Panel -->

        <?php
        require_once 'menu.phtml';
        ?>

        <!-- Left Panel -->

        <!-- Right Panel -->

        <div id="right-panel" class="right-panel">

            <!-- Header-->
            <?php
            require_once 'header.phtml';
            ?>
            <!-- Header-->

            <?php
            $this->getView($this->viewPath);
            ?>
        </div><!-- /#right-panel -->

        <!-- Right Panel -->

        <script src="<?= BASE_URL;?>lib/jquery/dist/jquery.min.js" type="text/javascript"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
        <script src="<?= BASE_URL;?>assets/js/jquery.mask.min.js"></script>
        <script src="<?= BASE_URL;?>lib/ckeditor/ckeditor.js"></script>
        <script src="<?= BASE_URL; ?>assets/js/main.js"></script>        
        <script src="<?= BASE_URL; ?>assets/js/admin.js"></script>


<!--        <script src="<?= BASE_URL;?>lib/chart.js/dist/Chart.bundle.min.js"></script>
        <script src="<?= BASE_URL;?>assets/js/dashboard.js"></script>
        <script src="<?= BASE_URL;?>assets/js/widgets.js"></script>
        <script src="<?= BASE_URL;?>lib/jqvmap/dist/jquery.vmap.min.js"></script>
        <script src="<?= BASE_URL;?>lib/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
        <script src="<?= BASE_URL;?>lib/jqvmap/dist/maps/jquery.vmap.world.js"></script>        
        <script>
            (function ($) {
                "use strict";

                jQuery('#vmap').vectorMap({
                    map: 'world_en',
                    backgroundColor: null,
                    color: '#ffffff',
                    hoverOpacity: 0.7,
                    selectedColor: '#1de9b6',
                    enableZoom: true,
                    showTooltip: true,
                    values: sample_data,
                    scaleColors: ['#1de9b6', '#03a9f5'],
                    normalizeFunction: 'polynomial'
                });
            })(jQuery);
        </script>-->
        <!--$this->getView($this->viewPath);-->

    </body>

</html>

