<aside id="left-panel" class="left-panel">
    <nav class="navbar navbar-expand-sm navbar-default">

        <div class="navbar-header">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-menu" aria-controls="main-menu" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="<?= BASE_URL; ?>admin"><img src="<?= BASE_URL; ?>images/logo.png" alt="Logo"></a>
            <a class="navbar-brand hidden" href="<?= BASE_URL; ?>admin"><img src="<?= BASE_URL; ?>images/logo2.png" alt="Logo"></a>
        </div>

        <div id="main-menu" class="main-menu collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="<?= BASE_URL; ?>admin"> <i class="menu-icon fa fa-dashboard"></i>Dashboard </a>
                </li>
                <h3 class="menu-title">Usuários</h3><!-- /.menu-title -->
                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-users"></i>Colaboradores</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-list"></i><a href="<?= BASE_URL; ?>admin/usuarios">Listar</a></li>
                        <li><i class="fa fa-plus-circle"></i><a href="<?= BASE_URL; ?>admin/usuarios/cadastro">Cadastrar</a></li>
                        <li><i class="fa fa-user"></i><a href="<?= BASE_URL; ?>admin/profile">Meu Perfil</a></li>
                    </ul>                    
                </li>
                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-users"></i>Clientes</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-list"></i><a href="<?= BASE_URL; ?>admin/clientes">Listar</a></li>
                    </ul>                    
                </li>
                <h3 class="menu-title">Estoque</h3><!-- /.menu-title -->
                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-shopping-bag"></i>Produtos</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-list"></i><a href="<?= BASE_URL; ?>admin/produtos">Listar</a></li>
                        <li><i class="fa fa-plus-circle"></i><a href="<?= BASE_URL; ?>admin/produtos/cadastro">Cadastrar</a></li>
                    </ul>                    
                </li> 
                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-tags"></i>Categorias</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-list"></i><a href="<?= BASE_URL; ?>admin/categorias">Listar</a></li>
                        <li><i class="fa fa-plus-circle"></i><a href="<?= BASE_URL; ?>admin/categorias/cadastro">Cadastrar</a></li>
                    </ul>                    
                </li> 
                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-barcode"></i>Fabricantes</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-list"></i><a href="<?= BASE_URL; ?>admin/fabricantes">Listar</a></li>
                        <li><i class="fa fa-plus-circle"></i><a href="<?= BASE_URL; ?>admin/fabricantes/cadastro">Cadastrar</a></li>
                    </ul>                    
                </li> 
                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-truck"></i>Fornecedores</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-list"></i><a href="<?= BASE_URL; ?>admin/fornecedores">Listar</a></li>
                        <li><i class="fa fa-plus-circle"></i><a href="<?= BASE_URL; ?>admin/fornecedores/cadastro">Cadastrar</a></li>
                    </ul>                    
                </li> 
                <h3 class="menu-title">Loja</h3><!-- /.menu-title -->
                <li class="menu-item">
                    <a href="<?= BASE_URL; ?>admin/loja"> <i class="menu-icon fa fa-gears"></i>Configurações</a>                                       
                    <a href="<?= BASE_URL; ?>admin/loja/seo"> <i class="menu-icon fa fa-search"></i>SEO</a>                                      
                </li>
                <li class="menu-item-has-children dropdown">                                   
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-sliders"></i>Customizar Páginas</a> 
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-television"></i><a href="<?= BASE_URL; ?>admin/customize/home">Home</a></li>
                        <li><i class="fa fa-television"></i><a href="<?= BASE_URL; ?>admin/customize/contato">Contato</a></li>
                    </ul> 
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </nav>
</aside><!-- /#left-panel -->