<header id="header"><!--header-->
    <div class="header_top"><!--header_top-->
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="contactinfo">
                        <ul class="nav nav-pills">
                            <li><a href="<?= BASE_URL; ?>contato"><i class="fa fa-phone"></i> <?= $this->viewData['loja']['telefone']; ?></a></li>
                            <li><a href="<?= BASE_URL; ?>contato"><i class="fa fa-envelope"></i> <?= $this->viewData['loja']['email']; ?></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="social-icons pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="<?= BASE_URL; ?>#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="<?= BASE_URL; ?>#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="<?= BASE_URL; ?>#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="<?= BASE_URL; ?>#"><i class="fa fa-dribbble"></i></a></li>
                            <li><a href="<?= BASE_URL; ?>#"><i class="fa fa-google-plus"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header_top-->

    <div class="header-middle"><!--header-middle-->
        <div class="container">
            <div class="row">
                <div class="col-md-4 clearfix">
                    <div class="logo pull-left">
                        <a href="<?= BASE_URL; ?>"><img src="<?= BASE_URL; ?>images/home/logo.png" alt="<?= $this->viewData['loja']['descricao']; ?>" /></a>
                    </div>                    
                </div>
                <div class="col-md-8 clearfix">
                    <div class="shop-menu clearfix pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="<?= BASE_URL; ?>account"><i class="fa fa-user"></i> Minha Conta</a></li>
                            <li><a href="<?= BASE_URL; ?>wishlist"><i class="fa fa-star"></i> Lista de Desejos</a></li>
                            <?php
                            $total_products = isset($_SESSION['cart']) ? $_SESSION['cart']['total'] : 0;
                            ?>
                            <li class="cart_total_products" data-products="<?= $total_products; ?>">
                                <a href="<?= BASE_URL; ?>cart">
                                    <i class="fa fa-shopping-cart"></i> Carrinho <span><?= $total_products; ?></span>
                                </a>
                            </li>
                            <?php
                            if (!isset($_SESSION['client']) && !filter_input(INPUT_COOKIE, 'clientlogin')):
                                ?>
                                <li><a href="<?= BASE_URL; ?>user/login"><i class="fa fa-lock"></i> Login</a></li>
                                <?php
                                else:
                                    ?>
                                <li><a href="<?= BASE_URL; ?>user/logout"><i class="fa fa-unlock"></i> Sair</a></li>
                                <?php
                            endif;
                            ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-middle-->

    <div class="header-bottom"><!--header-bottom-->
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="mainmenu pull-left">
                        <ul class="nav navbar-nav collapse navbar-collapse" style="max-height: 100%;">
                            <li><a href="<?= BASE_URL; ?>" class="active">Home</a></li>
                            <?php
                            $categorias = $this->viewData['categorias']->where('mae_categoria', null)->get()->toArray();
                            foreach ($categorias as $categoria):
                                echo '<li>';
                                echo '<a href="' . BASE_URL . 'category/' . $categoria['url_categoria'] . '">' . $categoria['titulo_categoria'] . '<i class="fa fa-angle-down"></i></a>';
                                $this->viewData['categorias']->listTreeMenuCatId($categoria["id_categoria"]);
                                echo '</li>';
                            endforeach;
                            ?>                            
                            <li><a href="<?= BASE_URL; ?>about-us.html">Sobre nós</a></li>
                            <li><a href="<?= BASE_URL; ?>contact-us.html">Contato</a></li>
                        </ul>                        
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="search_box pull-right">
                        <input type="text" placeholder="O que você procura?"/>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-bottom-->
</header><!--/header-->
<div class="modal fade" tabindex="-1" role="dialog" id="modal_add_product">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Item adicionado ao carrinho</h4>
            </div>
            <div class="modal-body">
                <p>O que você deseja fazer?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Continuar comprando</button>
                <a href="<?= BASE_URL ?>cart" class="btn btn-primary" title="Finalizar compra">Finalizar compra</a>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->