<header id="header"><!--header-->
    <div class="header_top"><!--header_top-->
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="contactinfo">
                        <ul class="nav nav-pills">
                            <li><a href="<?= BASE_URL; ?>contato"><i class="fa fa-phone"></i> <?= $this->viewData['loja']['telefone']; ?></a></li>
                            <li><a href="<?= BASE_URL; ?>contato"><i class="fa fa-envelope"></i> <?= $this->viewData['loja']['email']; ?></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="social-icons pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="<?= BASE_URL; ?>#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="<?= BASE_URL; ?>#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="<?= BASE_URL; ?>#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="<?= BASE_URL; ?>#"><i class="fa fa-dribbble"></i></a></li>
                            <li><a href="<?= BASE_URL; ?>#"><i class="fa fa-google-plus"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header_top-->

    <div class="header-middle"><!--header-middle-->
        <div class="container">
            <div class="row">
                <div class="col-md-4 clearfix">
                    <div class="logo pull-left">
                        <a href="<?= BASE_URL; ?>"><img src="<?= BASE_URL; ?>images/home/logo.png" alt="<?= $this->viewData['loja']['descricao']; ?>" /></a>
                    </div>                    
                </div>
                <div class="col-md-8 clearfix">
                    <div class="shop-menu clearfix pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="<?= BASE_URL; ?>account"><i class="fa fa-user"></i> Minha Conta</a></li>
                            <li><a href="<?= BASE_URL; ?>wishlist"><i class="fa fa-star"></i> Lista de Desejos</a></li>
                            <li><a href="<?= BASE_URL; ?>cart"><i class="fa fa-shopping-cart"></i> Carrinho</a></li>
                            <li><a href="<?= BASE_URL; ?>login"><i class="fa fa-lock"></i> Login</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-middle-->

    <div class="header-bottom"><!--header-bottom-->
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="mainmenu pull-left">
                        <ul class="nav navbar-nav collapse navbar-collapse" style="max-height: 100%;">
                            <li><a href="<?= BASE_URL; ?>" class="active">Home</a></li>
                            <?php
                            $categorias = $this->viewData['categorias']->where('mae_categoria', null)->get()->toArray();
                            foreach ($categorias as $categoria):
                                echo '<li>';
                                echo '<a href="' . BASE_URL . 'category/' . $categoria['url_categoria'] . '">' . $categoria['titulo_categoria'] . '<i class="fa fa-angle-down"></i></a>';
                                $this->viewData['categorias']->listTreeMenuCatId($categoria["id_categoria"]);
                                echo '</li>';
                            endforeach;
                            ?>                            
                            <li><a href="<?= BASE_URL; ?>about-us.html">Sobre nós</a></li>
                            <li><a href="<?= BASE_URL; ?>contact-us.html">Contato</a></li>
                        </ul>                        
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="search_box pull-right">
                        <input type="text" placeholder="O que você procura?"/>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-bottom-->
</header><!--/header-->