<?php

use App\Helpers\Local;
use App\Helpers\Seo;

$local = new Local;
$metaSeo = new Seo($local->getController(), $local->getAction());
?>
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">        
        <meta name="author" content="">
        <?= $metaSeo->getSeoTags(); ?>
        
        <link href="<?= BASE_URL;?>assets/css/bootstrap.min.css" rel="stylesheet">
        <link href="<?= BASE_URL;?>lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
        <link href="<?= BASE_URL;?>assets/css/prettyPhoto.css" rel="stylesheet">
        <link href="<?= BASE_URL;?>assets/css/price-range.css" rel="stylesheet">
        <link href="<?= BASE_URL;?>assets/css/animate.css" rel="stylesheet">
        <link href="<?= BASE_URL;?>assets/css/main.css" rel="stylesheet">
        <link href="<?= BASE_URL;?>assets/css/responsive.css" rel="stylesheet">
        <!--[if lt IE 9]>
        <script src="js/html5shiv.js"></script>
        <script src="js/respond.min.js"></script>
        <![endif]-->       
        <link rel="shortcut icon" href="<?= BASE_URL;?>images/ico/favicon.ico">
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?= BASE_URL;?>images/ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?= BASE_URL;?>images/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?= BASE_URL;?>images/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="<?= BASE_URL;?>images/ico/apple-touch-icon-57-precomposed.png">
    </head><!--/head-->

    <body>
        <?php
        $this->getView($this->viewPath);
        ?>
        <script src="<?= BASE_URL;?>assets/js/jquery.js"></script>
        <script src="<?= BASE_URL;?>assets/js/bootstrap.min.js"></script>
        <script src="<?= BASE_URL;?>assets/js/jquery.scrollUp.min.js"></script>
        <script src="<?= BASE_URL;?>assets/js/price-range.js"></script>
        <script src="<?= BASE_URL;?>assets/js/jquery.prettyPhoto.js"></script>
        <script src="<?= BASE_URL;?>assets/js/e-shopper.js"></script>
    </body>
</html>