<div class="breadcrumbs">
    <div class="col-sm-4">
        <div class="page-header float-left">
            <div class="page-title">
                <h1>Dashboard</h1>
            </div>
        </div>
    </div>
    <div class="col-sm-8">
        <div class="page-header float-right">
            <div class="page-title">
                <ol class="breadcrumb text-right">
                    <li><a href="<?= BASE_URL; ?>admin/">Dashboard</a></li>
                    <li><a href="<?= BASE_URL; ?>admin/categorias">Categorias</a></li>
                    <li class="active"><a href="<?= BASE_URL; ?>admin/categorias/cadastro">Cadastrar</a></li>
                </ol>
            </div>
        </div>
    </div>
</div>   

<div class="content mt-3">
    <div class="animated fadeIn"> 
        <form method="post" name="cadastra_categorias" enctype="multipart/form-data">            
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header"><strong>Dados </strong><small> da categoria</small></div>
                    <div class="card-body card-block">
                        <div class="form-group">
                            <label class=" form-control-label">Título</label>
                            <input type="text" name="titulo_categoria" placeholder="Digite um título para a categoria" class="form-control">
                        </div> 
                        <div class="form-group">
                            <label class=" form-control-label">URL</label>
                            <input type="text" name="url_categoria" placeholder="Personalizar URL da categoria" class="form-control">
                            <span class="font-weight-light text-muted">Este campo não é obrigatório</span>
                        </div> 
                        <div class="form-group">
                            <label  class=" form-control-label">Categoria mãe</label>
                            <select class="custom-select" name="mae_categoria">
                                <option value="">Criar categoria principal</option>
                                <?php
                                $categorias = $this->viewData->where('mae_categoria', null)->get()->toArray();
                                foreach ($categorias as $cat):
                                    echo '<option value="' . $cat['id_categoria'] . '">' . $cat['titulo_categoria'] . '</option>';
                                    $this->viewData->listTreeCatId($cat["id_categoria"]);
                                endforeach;
                                ?>
                            </select>
                            <span class="font-weight-light text-muted">Para criar uma subcategoria selecione uma categoria mãe</span>
                        </div>
                        <span>Status</span>
                        <div class="form-group">                            
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" checked name="ativo_categoria" id="inlineRadio1" value="1">
                                <label class="form-check-label" for="inlineRadio1">ativada</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="ativo_categoria" id="inlineRadio2" value="0">
                                <label class="form-check-label" for="inlineRadio2">desativada</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12">
                <div class="card">
                    <div class="card-header"><strong>Enviar formulário</strong></div>
                    <div class="card-body card-block">
                        <button type="submit" class="btn btn-success btn-large">Cadastrar categoria</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div><!-- .animated -->
</div><!-- .content -->
<div class="modal fade" tabindex="-1" data-keyboard="false" data-backdrop="static" role="dialog" id="modal_categorias_cad">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Cadastro de categoria</h5>
                <button type="button" class="close btn_close close_modal" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p><i class="fa fa-spinner fa-spin fa-2x fa-fw"></i>Salvando categoria...</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger btn_close close_modal" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>
