<div class="breadcrumbs">
    <div class="col-sm-4">
        <div class="page-header float-left">
            <div class="page-title">
                <h1>Dashboard</h1>
            </div>
        </div>
    </div>
    <div class="col-sm-8">
        <div class="page-header float-right">
            <div class="page-title">
                <ol class="breadcrumb text-right">
                    <li><a href="<?= BASE_URL; ?>admin/">Dashboard</a></li>
                    <li><a href="<?= BASE_URL; ?>admin/categorias">Categorias</a></li>
                    <li class="active">Índice</li>
                </ol>
            </div>
        </div>
    </div>
</div>   
<div class="content mt-3">
    <div class="animated fadeIn">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <strong class="card-title">Categorias</strong>
                </div>
                <div class="card-body  table-responsive">
                    <table class="table">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Título</th>
                                <th scope="col">URL</th>
                                <th scope="col">Categoria Mãe</th>
                                <th scope="col">Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $mae = new App\Models\Admin\Categorias;
                            foreach ($this->viewData['categorias'] as $cat):
                                ?>
                                <tr id="<?= $cat['id_categoria']; ?>">
                                    <th scope="row"><?= $cat['id_categoria']; ?></th>
                                    <td><?= ucfirst($cat['titulo_categoria']); ?></td>
                                    <td><?= $cat['url_categoria']; ?></td>
                                    <td><?= $mae->getCat($cat['mae_categoria'])['titulo_categoria']; ?></td>
                                    <td>
                                        <a href="<?= BASE_URL; ?>admin/categorias/editar/<?= $cat['id_categoria']; ?>" class="btn btn-success" title="editar categoria"><i class="fa fa-edit"></i> editar</a>
                                        <a href="#" class="btn btn-danger cat_delete" id="<?= $cat['id_categoria']; ?>" title="excluir categoria" data-name="<?= $cat['titulo_categoria']; ?>"><i class="fa fa-trash"></i> excluir</a>
                                    </td>
                                </tr>                                
                                <?php
                            endforeach;
                            ?>
                        </tbody>
                    </table>
                    <?php
                    $pager = new App\Helpers\Pager($this->viewData['pagina'], $this->viewData['paginas'], $this->viewData['limit'], $this->viewData['offset'], 'admin/categorias/pagina');
                    echo $pager->showPager();
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" tabindex="-1" data-keyboard="false" data-backdrop="static" role="dialog" id="modal_categorias_del">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Exclusão de categoria</h5>
                <button type="button" class="close btn_close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p><i class="fa fa-spinner fa-spin fa-2x fa-fw"></i>Excluindo categoria...</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger btn_close" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>
