<div class="breadcrumbs">
    <div class="col-sm-4">
        <div class="page-header float-left">
            <div class="page-title">
                <h1>Dashboard</h1>
            </div>
        </div>
    </div>
    <div class="col-sm-8">
        <div class="page-header float-right">
            <div class="page-title">
                <ol class="breadcrumb text-right">
                    <li><a href="<?= BASE_URL; ?>admin/">Dashboard</a></li>
                    <li><a href="<?= BASE_URL; ?>admin/loja">Loja</a></li>
                    <li class="active">Configurações</li>
                </ol>
            </div>
        </div>
    </div>
</div>   

<div class="content mt-3">
    <div class="animated fadeIn">        
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <strong class="card-title">Lista de páginas possíveis de otimizar</strong>
                </div>
                <div class="card-body table-responsive">
                    <table class="table">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col">Página</th>
                                <th scope="col">Título da página</th>
                                <th scope="col">URL</th>
                                <th scope="col">Imagem</th>
                                <th scope="col">Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($this->viewData as $page):
                                extract($page);
                                ?>
                                <tr>
                                    <td><?= $nome; ?></td>
                                    <td><?= $titulo; ?></td>
                                    <td><?= $url; ?></td>
                                    <td><?= $image; ?></td>
                                    <td>
                                        <a href="<?= BASE_URL;?>admin/loja/edit_page/<?= $id; ?>" class="btn btn-success" title="Editar Página <?= $nome; ?>">
                                            <i class="fa fa-edit"></i> Editar
                                        </a> 
                                        <a href="<?= BASE_URL.$url; ?>" title="Ver Página <?= $nome; ?>"  class="btn btn-info">
                                            <i class="fa fa-tv"></i> Ver
                                        </a>
                                    </td>
                                </tr> 
                                <?php
                            endforeach;
                            ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div><!-- .animated -->
    </div><!-- .content -->
