<?php
extract($this->viewData);
?>
<div class="breadcrumbs">
    <div class="col-sm-4">
        <div class="page-header float-left">
            <div class="page-title">
                <h1>Dashboard</h1>
            </div>
        </div>
    </div>
    <div class="col-sm-8">
        <div class="page-header float-right">
            <div class="page-title">
                <ol class="breadcrumb text-right">
                    <li><a href="<?= BASE_URL; ?>admin/">Dashboard</a></li>
                    <li><a href="<?= BASE_URL; ?>admin/fabricantes">Fabricantes</a></li>
                    <li class="active">Atualizar</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="content mt-3">
    <div class="animated fadeIn">
<!--        <div class="col-12">
            <div class="debug"></div>
        </div>-->
        <form method="post" name="atualiza_marcas" enctype="multipart/form-data">         
            <div class="col-12">
                <div class="card">
                    <div class="card-header">Edição de <strong>Fabricantes e Marcas</strong> de produtos</div>
                    <div class="card-body card-block">
                        <div class="form-group">
                            <label for="company" class=" form-control-label">Título</label>
                            <input type="text" id="company" value="<?= $titulo_marca; ?>" name="titulo_marca" placeholder="Digite o título da marca ou fabricante de produtos" class="form-control">
                        </div> 
                    </div>
                    <div class="card-footer">
                        <div class="card-body card-block">
                            <button type="submit" class="btn btn-success btn-large">Atualizar Marca/Fabricante</button>
                            <input type="hidden" value="<?= $id_marca;?>" name="id_marca">
                        </div>
                    </div>
                </div>
            </div>            
        </form>
    </div>
</div>
<div class="modal fade" tabindex="-1" data-keyboard="false" data-backdrop="static" role="dialog" id="modal_fabricantes_edit">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Edição de Marcas e Fabricantes</h5>
                <button type="button" class="close btn_close close_modal" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p><i class="fa fa-spinner fa-spin fa-2x fa-fw"></i>Atualizando fabricante...</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger btn_close close_modal" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>